
[Potential MW]
file = ./auxiliary/MWPotentialHunter24_axi.ini

[potential LMC]
type=spheroid
gamma=1
beta=3
alpha=1
scaleradius=10.8
outercutoffradius=108
mass=1.5e11
center=./auxiliary/trajlmc.txt

[potential acc]
# time-dependent acceleration of the Milky Way-centered reference frame
type=UniformAcceleration
file=./auxiliary/accel.txt
